function(theos_install_headers target_name)
    file(GLOB_RECURSE headers RELATIVE ${CMAKE_SOURCE_DIR}/Includes/${traget_name} "*.h")
    foreach(header ${headers})
        get_filename_component(subdirectory ${header} DIRECTORY)
        install(FILES ${header} DESTINATION usr/include/${target_name}/${subdirectory})
    endforeach()
endfunction()

function(theos_install_sources target_name)
    file(GLOB_RECURSE sources RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.h" "*.c")
    foreach(source ${sources})
        get_filename_component(subdirectory ${source} DIRECTORY)
        install(FILES ${source} DESTINATION usr/src/theos/${target_name}/${subdirectory})
    endforeach()
endfunction()

function(theos_generated_sources target_name)
    if(DEFINED GENERATED_SOURCES)
        set_source_files_properties(${GENERATED_SOURCES} PROPERTIES GENERATED 1)
        foreach(generated ${GENERATED_SOURCES})
            get_filename_component(generated_name ${generated} NAME)
            add_dependencies(${target_name} generate_${generated_name})
        endforeach()
    endif()
endfunction()

function(theos_lib target_name fs_name)
    theos_install_headers(${target_name})
    theos_install_sources("Userland/Libraries/${target_name}")
    add_library(${target_name} SHARED ${SOURCES} ${GENERATED_SOURCES})
    install(TARGETS ${target_name} DESTINATION usr/lib)
    set_target_properties(${target_name} PROPERTIES OUTPUT_NAME ${fs_name})
    theos_generated_sources(${target_name})
endfunction()

function(theos_shared_lib target_name fs_name)
    theos_install_headers(${target_name})
    theos_install_sources("Userland/Libraries/${target_name}")
    add_library(${target_name} SHARED ${SOURCES} ${GENERATED_SOURCES})
    install(TARGETS ${target_name} DESTINATION usr/lib)
    set_target_properties(${target_name} PROPERTIES OUTPUT_NAME ${fs_name})
    theos_generated_sources(${target_name})
endfunction()

function(theos_libc target_name fs_name)
    theos_install_headers(${target_name})
    theos_install_sources("Userland/Libraries/LibC")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -nostdlib -fpic")
    add_library(${target_name} SHARED ${SOURCES})
    install(TARGETS ${target_name} DESTINATION usr/lib)
    set_target_properties(${target_name} PROPERTIES OUTPUT_NAME ${fs_name})
    target_link_directories(LibC PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
    theos_generated_sources(${target_name})
endfunction()

function(theos_libc_static target_name fs_name)
    theos_install_headers(${target_name})
    theos_install_sources("Userland/Libraries/LibC")
    add_library(${target_name} ${SOURCES})
    install(TARGETS ${target_name} ARCHIVE DESTINATION usr/lib)
    set_target_properties(${target_name} PROPERTIES OUTPUT_NAME ${fs_name})
    target_link_directories(${target_name} PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
    theos_generated_sources(${target_name})
endfunction()

function(theos_bin target_name)
    add_executable(${target_name} ${SOURCES})
    install(TARGETS ${target_name} RUNTIME DESTINATION bin)
    theos_generated_sources(${target_name})
endfunction()

function(theos_app target_name)
    theos_bin("${target_name}")
endfunction()
